ci: package dynamic and static libs in release artifacts

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -67,6 +67,11 @@ jobs:
           cmake .. -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON
           cmake --build . --config Release
 
+          # Build static archive variant for development/linking use.
+          cd ..
+          cmake -S . -B build-static -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=OFF
+          cmake --build build-static --config Release
+
       - name: Get commit hash
         id: commit
         if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
@@ -86,6 +91,12 @@ jobs:
         run: |
           cp ggml/LICENSE ./build/bin/ggml.txt
           cp LICENSE ./build/bin/stable-diffusion.cpp.txt
+          static_lib_path="$(find ./build-static -type f -name 'libstable-diffusion.a' | head -n 1)"
+          if [ -z "$static_lib_path" ]; then
+            echo "Can't find libstable-diffusion.a"
+            exit 1
+          fi
+          cp "$static_lib_path" ./build/bin/libstable-diffusion.a
           zip -j sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip ./build/bin/*
 
       - name: Upload artifacts
@@ -120,6 +131,11 @@ jobs:
           cmake .. -DSD_BUILD_SHARED_LIBS=ON -DSD_VULKAN=ON
           cmake --build . --config Release
 
+          # Build static archive variant for development/linking use.
+          cd ..
+          cmake -S . -B build-static -DSD_BUILD_SHARED_LIBS=OFF -DSD_VULKAN=ON
+          cmake --build build-static --config Release
+
       - name: Get commit hash
         id: commit
         if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
@@ -139,6 +155,12 @@ jobs:
         run: |
           cp ggml/LICENSE ./build/bin/ggml.txt
           cp LICENSE ./build/bin/stable-diffusion.cpp.txt
+          static_lib_path="$(find ./build-static -type f -name 'libstable-diffusion.a' | head -n 1)"
+          if [ -z "$static_lib_path" ]; then
+            echo "Can't find libstable-diffusion.a"
+            exit 1
+          fi
+          cp "$static_lib_path" ./build/bin/libstable-diffusion.a
           zip -j sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}-vulkan.zip ./build/bin/*
 
       - name: Upload artifacts
@@ -237,6 +259,11 @@ jobs:
           cmake .. -DGGML_AVX2=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSD_BUILD_SHARED_LIBS=ON
           cmake --build . --config Release
 
+          # Build static archive variant for development/linking use.
+          cd ..
+          cmake -S . -B build-static -DGGML_AVX2=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DSD_BUILD_SHARED_LIBS=OFF
+          cmake --build build-static --config Release
+
       - name: Get commit hash
         id: commit
         if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
@@ -256,6 +283,12 @@ jobs:
         run: |
           cp ggml/LICENSE ./build/bin/ggml.txt
           cp LICENSE ./build/bin/stable-diffusion.cpp.txt
+          static_lib_path="$(find ./build-static -type f -name 'libstable-diffusion.a' | head -n 1)"
+          if [ -z "$static_lib_path" ]; then
+            echo "Can't find libstable-diffusion.a"
+            exit 1
+          fi
+          cp "$static_lib_path" ./build/bin/libstable-diffusion.a
           zip -j sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-${{ steps.system-info.outputs.OS_NAME }}-${{ steps.system-info.outputs.OS_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}.zip ./build/bin/*
 
       - name: Upload artifacts
@@ -284,7 +317,7 @@ jobs:
           - build: "avx512"
             defines: "-DGGML_NATIVE=OFF -DGGML_AVX512=ON -DGGML_AVX=ON -DGGML_AVX2=ON -DSD_BUILD_SHARED_LIBS=ON"
           - build: "cuda12"
-            defines: "-DSD_CUDA=ON -DSD_BUILD_SHARED_LIBS=ON -DCMAKE_CUDA_ARCHITECTURES='61;70;75;80;86;89;90;100;120' -DCMAKE_CUDA_FLAGS='-Xcudafe \"--diag_suppress=177\" -Xcudafe \"--diag_suppress=550\"'"
+            defines: '-DSD_CUDA=ON -DSD_BUILD_SHARED_LIBS=ON -DCMAKE_CUDA_ARCHITECTURES=''61;70;75;80;86;89;90;100;120'' -DCMAKE_CUDA_FLAGS=''-Xcudafe "--diag_suppress=177" -Xcudafe "--diag_suppress=550"'''
           - build: "vulkan"
             defines: "-DSD_VULKAN=ON -DSD_BUILD_SHARED_LIBS=ON"
     steps:
@@ -347,19 +380,31 @@ jobs:
         if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
         run: |
           $filePath = ".\build\bin\Release\*"
+          $binDir = ".\build\bin\Release"
           if (Test-Path $filePath) {
             echo "Exists at path $filePath"
-            Copy-Item ggml/LICENSE .\build\bin\Release\ggml.txt
-            Copy-Item LICENSE .\build\bin\Release\stable-diffusion.cpp.txt
+            Copy-Item ggml/LICENSE "$binDir\ggml.txt"
+            Copy-Item LICENSE "$binDir\stable-diffusion.cpp.txt"
           } elseif (Test-Path ".\build\bin\stable-diffusion.dll") {
-          $filePath = ".\build\bin\*"
+            $filePath = ".\build\bin\*"
+            $binDir = ".\build\bin"
             echo "Exists at path $filePath"
-            Copy-Item ggml/LICENSE .\build\bin\ggml.txt
-            Copy-Item LICENSE .\build\bin\stable-diffusion.cpp.txt
+            Copy-Item ggml/LICENSE "$binDir\ggml.txt"
+            Copy-Item LICENSE "$binDir\stable-diffusion.cpp.txt"
           } else {
             ls .\build\bin
             throw "Can't find stable-diffusion.dll"
           }
+
+          # Include import library for Windows consumers linking against the DLL.
+          $importLib = Get-ChildItem -Path .\build -Recurse -Filter stable-diffusion.lib -File |
+            Where-Object { $_.FullName -notmatch '\\_deps\\' } |
+            Select-Object -First 1
+          if ($null -eq $importLib) {
+            throw "Can't find stable-diffusion.lib"
+          }
+          Copy-Item $importLib.FullName "$binDir\stable-diffusion.lib" -Force
+
           7z a sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-win-${{ matrix.build }}-x64.zip $filePath
 
       - name: Copy and pack Cuda runtime
@@ -475,6 +520,16 @@ jobs:
           cp "${env:HIP_PATH}\bin\rocblas.dll" "build\bin\"
           cp "${env:HIP_PATH}\bin\rocblas\library\*" "build\bin\rocblas\library\"
           cp "${env:HIP_PATH}\bin\hipblaslt\library\*" "build\bin\hipblaslt\library\"
+
+          # Include import library for Windows consumers linking against the DLL.
+          $importLib = Get-ChildItem -Path .\build -Recurse -Filter stable-diffusion.lib -File |
+            Where-Object { $_.FullName -notmatch '\\_deps\\' } |
+            Select-Object -First 1
+          if ($null -eq $importLib) {
+            throw "Can't find stable-diffusion.lib"
+          }
+          cp $importLib.FullName "build\bin\stable-diffusion.lib"
+
           7z a sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-win-rocm-x64.zip .\build\bin\*
 
       - name: Upload artifacts
@@ -578,6 +633,20 @@ jobs:
             -DSD_BUILD_SHARED_LIBS=ON
           cmake --build . --config Release
 
+          # Build static archive variant for development/linking use.
+          cd ..
+          cmake -S . -B build-static -G Ninja \
+            -DCMAKE_CXX_COMPILER=amdclang++ \
+            -DCMAKE_C_COMPILER=amdclang \
+            -DCMAKE_BUILD_TYPE=Release \
+            -DSD_HIPBLAS=ON \
+            -DGPU_TARGETS="${{ env.GPU_TARGETS }}" \
+            -DAMDGPU_TARGETS="${{ env.GPU_TARGETS }}" \
+            -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
+            -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
+            -DSD_BUILD_SHARED_LIBS=OFF
+          cmake --build build-static --config Release
+
       - name: Get commit hash
         id: commit
         if: ${{ ( github.event_name == 'push' && github.ref == 'refs/heads/master' ) || github.event.inputs.create_release == 'true' }}
@@ -615,6 +684,12 @@ jobs:
         run: |
           cp ggml/LICENSE ./build/bin/ggml.txt
           cp LICENSE ./build/bin/stable-diffusion.cpp.txt
+          static_lib_path="$(find ./build-static -type f -name 'libstable-diffusion.a' | head -n 1)"
+          if [ -z "$static_lib_path" ]; then
+            echo "Can't find libstable-diffusion.a"
+            exit 1
+          fi
+          cp "$static_lib_path" ./build/bin/libstable-diffusion.a
           zip -y -r sd-${{ env.BRANCH_NAME }}-${{ steps.commit.outputs.short }}-bin-${{ steps.system-info.outputs.OS_TYPE }}-Ubuntu-${{ env.UBUNTU_VERSION }}-${{ steps.system-info.outputs.CPU_ARCH }}-rocm.zip ./build/bin
 
       - name: Upload artifacts
